apiVersion: v1
kind: pod
metadata:
  name: debug
  namespace: roboshop
spec:
# list of conatiners
  containers:
  - name: debug
    image: guru/debug:v1
    #here with this line port will not be opned, just for information
    command: ["sleep", "100000"]